<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ABML-Articulo.aspx.cs" Inherits="e_commerce.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="dgvArticulos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" OnSelectedIndexChanging="dgvArticulos_SelectedIndexChanging" AutoGenerateSelectButton="True" OnRowCancelingEdit="dgvArticulos_RowCancelingEdit" OnRowDeleting="dgvArticulos_RowDeleting" OnRowEditing="dgvArticulos_RowEditing" OnRowUpdating="dgvArticulos_RowUpdating">
        <Columns>
            <asp:TemplateField HeaderText="ID">
                <EditItemTemplate>
                    <asp:Label ID="lbl_eit_Id" runat="server" Text='<%# Bind("ID") %>'></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Id" runat="server" Text='<%# Bind("ID") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="NOMBRE">
                <EditItemTemplate>
                    <asp:TextBox ID="tbx_Nombre" runat="server" Text='<%# Bind("NOMBRE") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Nombre" runat="server" Text='<%# Bind("NOMBRE") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PRECIO">
                <EditItemTemplate>
                    <asp:TextBox ID="tbx_eit_Precio" runat="server" Text='<%# Bind("PRECIO") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Precio" runat="server" Text='<%# Bind("PRECIO") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="CANTIDAD">
                <EditItemTemplate>
                    <asp:TextBox ID="tbx_eit_Cantidad" runat="server" Text='<%# Bind("CANTIDAD") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Cantidad" runat="server" Text='<%# Bind("CANTIDAD") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="IMAGEN">
                <EditItemTemplate>
                    <asp:TextBox ID="tbx_eit_Imagen" runat="server" Text='<%# Bind("IMAGEN") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_imagen" runat="server" Text='<%# Bind("IMAGEN") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="CATEGORIA">
                <EditItemTemplate>
                    <asp:DropDownList ID="ddl_eit_Categoria" runat="server" DataSourceID="SqlDataSource1" DataTextField="NOMBRE" DataValueField="ID">
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LUNARSOFT_DBConnectionString %>" SelectCommand="SELECT [ID], [NOMBRE] FROM [CATEGORIAS]"></asp:SqlDataSource>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Categoria" runat="server" Text='<%# Bind("CATEGORIA") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="COMPOSICION">
                <EditItemTemplate>
                    <asp:DropDownList ID="ddl_eit_Composicion" runat="server" DataSourceID="SqlDataSource2" DataTextField="NOMBRE" DataValueField="ID">
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:LUNARSOFT_DBConnectionString %>" SelectCommand="SELECT [ID], [NOMBRE] FROM [COMPOSICIONES]"></asp:SqlDataSource>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Composicion" runat="server" Text='<%# Bind("COMPOSICION") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="MEDIDA">
                <EditItemTemplate>
                    <asp:DropDownList ID="ddl_eit_Medida" runat="server" DataSourceID="SqlDataSource3" DataTextField="NOMBRE" DataValueField="ID">
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:LUNARSOFT_DBConnectionString %>" SelectCommand="SELECT ID, ISNULL(MEDIDAS.NOMBRE, MEDIDAS.ANCHO_CM+'x'+MEDIDAS.LARGO_CM) AS NOMBRE, MEDIDAS.LARGO_CM, MEDIDAS.ANCHO_CM FROM MEDIDAS"></asp:SqlDataSource>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Medida" runat="server" Text='<%# Bind("MEDIDA") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="ESTILO">
                <EditItemTemplate>
                    <asp:DropDownList ID="ddl_eit_Estilo" runat="server" DataSourceID="SqlDataSource4" DataTextField="NOMBRE" DataValueField="ID">
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:LUNARSOFT_DBConnectionString %>" SelectCommand="SELECT [ID], [NOMBRE] FROM [ESTILOS]"></asp:SqlDataSource>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Estilo" runat="server" Text='<%# Bind("ESTILO") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="COLOR">
                <EditItemTemplate>
                    <asp:DropDownList ID="ddl_eit_Color" runat="server" DataSourceID="SqlDataSource5" DataTextField="NOMBRE" DataValueField="ID">
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource5" runat="server" ConnectionString="<%$ ConnectionStrings:LUNARSOFT_DBConnectionString %>" SelectCommand="SELECT [ID], [NOMBRE], [CODIGO] FROM [COLORES]"></asp:SqlDataSource>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Color" runat="server" Text='<%# Bind("COLOR") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
        <RowStyle BackColor="White" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="Gray" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
    </asp:GridView>
    <asp:Label ID="lblMensaje" runat="server"></asp:Label>
</asp:Content>
