use LUNARSOFT_DB
--
INSERT INTO CATEGORIAS VALUES ('Sábanas')
INSERT INTO CATEGORIAS VALUES ('Acolchados')
INSERT INTO CATEGORIAS VALUES ('Almohadas')
--
INSERT INTO ESTILOS VALUES ('Liso')
INSERT INTO ESTILOS VALUES ('Estampado')
--
INSERT INTO COMPOSICIONES VALUES ('Algodón')
INSERT INTO COMPOSICIONES VALUES ('Poliéster')
--
INSERT INTO COLORES VALUES ('blanco')
INSERT INTO COLORES VALUES ('negro')
INSERT INTO COLORES VALUES ('gris')
INSERT INTO COLORES VALUES ('rosa')
INSERT INTO COLORES VALUES ('rojo')
INSERT INTO COLORES VALUES ('lila')
INSERT INTO COLORES VALUES ('amarillo')
INSERT INTO COLORES VALUES ('verde')
INSERT INTO COLORES VALUES ('azul')
INSERT INTO COLORES VALUES ('violeta')
INSERT INTO COLORES VALUES ('marron')
INSERT INTO COLORES VALUES ('naranja')
INSERT INTO COLORES VALUES ('turquesa')
INSERT INTO COLORES VALUES ('celeste')
--
INSERT INTO MEDIDAS (NOMBRE, LARGO_CM, ANCHO_CM) VALUES ('1 plaza', '190', '100')
INSERT INTO MEDIDAS (NOMBRE, LARGO_CM, ANCHO_CM) VALUES ('2 plazas', '190', '135')
INSERT INTO MEDIDAS (NOMBRE, LARGO_CM, ANCHO_CM) VALUES ('Queen ', '190', '150')
INSERT INTO MEDIDAS (NOMBRE, LARGO_CM, ANCHO_CM) VALUES ('King', '190', '200')
INSERT INTO MEDIDAS (LARGO_CM, ANCHO_CM) VALUES ('40', '70')
INSERT INTO MEDIDAS (LARGO_CM, ANCHO_CM) VALUES ('50', '70')
INSERT INTO MEDIDAS (LARGO_CM, ANCHO_CM) VALUES ('50', '90')
--
INSERT INTO ESTADOS VALUES ('En preparación')
INSERT INTO ESTADOS VALUES ('Enviado')
INSERT INTO ESTADOS VALUES ('Entregado')
--
INSERT INTO MEDIOS_DE_PAGO VALUES ('EFECTIVO')
INSERT INTO MEDIOS_DE_PAGO VALUES ('VISA DÉBITO')
INSERT INTO MEDIOS_DE_PAGO VALUES ('MAESTRO')
INSERT INTO MEDIOS_DE_PAGO VALUES ('VISA CRÉDITO')
INSERT INTO MEDIOS_DE_PAGO VALUES ('MASTERCARD CRÉDITO')
INSERT INTO MEDIOS_DE_PAGO VALUES ('AMERICAN EXPRESS CREDITO')
INSERT INTO MEDIOS_DE_PAGO VALUES ('MC-DEBIT')
--
SET DATEFORMAT dmy
INSERT INTO USUARIOS (NOMBRE, APELLIDO, DNI, MAIL, TELEFONO, NACIMIENTO, CONTRASEÑA) VALUES('admin', 'admin','11111111', 'admin@gmail.com','0123456789', '20/11/1997', 'admin')
INSERT INTO USUARIOS (NOMBRE, APELLIDO, DNI, MAIL, TELEFONO, NACIMIENTO, CONTRASEÑA) VALUES('tomas', 'diaz','40135346', 'tomas.dias@gmail.com','1517756815', '20/11/1997', '123456')
INSERT INTO USUARIOS (NOMBRE, APELLIDO, DNI, MAIL, TELEFONO, NACIMIENTO, CONTRASEÑA) VALUES('lautaro', 'villalva','40130286', 'ljvillalva@gmail.com','1537756615', '18/1/1997', '123456')
INSERT INTO USUARIOS (NOMBRE, APELLIDO, DNI, MAIL, TELEFONO, NACIMIENTO, CONTRASEÑA) VALUES('ayelen', 'perez', '40861673', 'ayepe@gmail.com', '1583729481', '7/10/1997', '123456')
INSERT INTO USUARIOS (NOMBRE, APELLIDO, DNI, MAIL, TELEFONO, NACIMIENTO, CONTRASEÑA) VALUES('marcos', 'leal', '41394282', 'mleal@gmail.com', '1506963211', '9/04/1997', '123456')
INSERT INTO USUARIOS (NOMBRE, APELLIDO, DNI, MAIL, TELEFONO, NACIMIENTO, CONTRASEÑA) VALUES('sol', 'franco', '39104837', 'franco.sol@hotmail.com', '1547592857', '10/10/1996', '223456')
--
